# -*- coding: utf-8 -*-
"""Взгляд машины знаний, адаптированный под уровни «Просто» и «Популярно».

Владелец 09.09: «адаптируй тоже для простого, популярного и продвинутого результат машины
знаний». Продвинутый текст — в ns_km.py; здесь те же пять направлений, те же опоры,
но словами читателя каждого уровня. Опоры (based_on) те же, что у продвинутого.
"""
from ns_km import (W_SINK, W_CLOUD, W_LIGHTV, W_TABLE, W_BOMB, W_ARROW, W_HOURGL, W_ERASER,
                   W_FRICT, W_LEAP, W_RINGS, W_DISORD, W_BOTTOM, W_DANCE)

B1, B2, B3, B4, B5 = ([W_SINK, W_CLOUD, W_LIGHTV, W_TABLE], [W_ARROW, W_HOURGL, W_ERASER],
                      [W_FRICT, W_LEAP, W_RINGS, W_DISORD], [W_BOMB, W_BOTTOM, W_DANCE], [W_LIGHTV, W_CLOUD])

TIERS = {
"ru": {
 "simple": {
    "seen": "Построен водоворот, который за конечное время разгоняется до бесконечности, хотя энергии в нём всё меньше. Толкает его гладкая внешняя сила, а недостающую силу вода производит сама, мелкими колебаниями вокруг ядра. Для нас это первая честно построенная точка, где обычное описание жидкости ломается, и с ней можно работать дальше.",
    "strength": "Механизм виден целиком: игла, кольцо вокруг неё, колебания, спокойная вода снаружи. Что видно, то можно посчитать по-другому, повторить в другой среде и попробовать собрать руками.",
    "directions": [
        {"text": "Связь с гравитацией. Уже сорок лет известно: волны в текущей воде ведут себя так, будто пространство вокруг искривлено, и в ванне или в облаке холодных атомов делают настоящие «горизонты» как у чёрной дыры. Значит, у иглы из этой работы тоже есть своя «кривизна», и её можно посчитать. Если в точке взрыва она уходит в бесконечность, перед нами лабораторная модель сингулярности, как в общей теории относительности, только с конечной энергией. Оговорка честная: это модель того, как ведут себя волны, а не сама гравитация Эйнштейна.", "based_on": B1},
        {"text": "Точка, где порядок может рождаться из хаоса. Есть мысль: в такой особой точке второе начало термодинамики может перестать быть строгим, и беспорядок там не растёт, а убывает. У этой работы это можно проверить прямо: посчитать, сколько беспорядка рождается отдельно в игле, в кольце и снаружи. Энергию в воду вносит внешняя сила, поэтому в целом беспорядок растёт; вопрос, есть ли внутри область, где он падает и удерживается колебаниями. Если есть, «центр антиэнтропии» станет не словами, а числом.", "based_on": B2},
        {"text": "Жидкость без трения. В обычной воде трение гасит колебания, и на этом построено доказательство. А в сверхтекучем гелии и в конденсате Бозе–Эйнштейна трения нет: вихри там квантованы, сами выстраиваются в решётки, а квантовая турбулентность, порядок среди хаоса, наблюдается в лаборатории. Отсюда идея: там, где нечему гасить, особая точка может не рассеяться, а удержаться. Это можно проверить на уравнении, которым описывают конденсат.", "based_on": B3},
        {"text": "Установка на столе. Два колеса, вращающиеся навстречу друг другу, создают именно такое течение со сдвигом, на котором в работе растут колебания. Измерить можно одно конкретное число: как колебания в кольце переносят вращение при разной скорости колёс. Совпадение с расчётом было бы первой точкой из лаборатории. Похожие измерения уже делали на водовороте в чашке.", "based_on": B4},
        {"text": "Два пути к одной двери. Установка с колёсами и сверхтекучая жидкость описываются одной и той же математикой: у обеих есть вращение со сдвигом, кольцо и колебания. Стоит составить таблицу: что в игле отвечает горизонту, что квантованному вихрю, что внешней накачке. Тогда видно, какой путь ближе к опыту, а какой к теории.", "based_on": B5},
    ],
    "ideas": [
        "Посчитать «кривизну» иглы как для волн в воде и посмотреть, уходит ли она в бесконечность в момент взрыва.",
        "Посчитать, где именно в конструкции рождается беспорядок, а где, возможно, убывает.",
        "Повторить механизм колебаний в модели конденсата, где трения нет.",
        "Собрать бак с двумя встречными приводами и измерить перенос вращения в кольце.",
    ],
    "significance": "Если особая точка в воде переносится на «кривизну», обычная и квантовая жидкость становятся стендом для вопросов, которые в настоящей гравитации не проверить: как ведёт себя беспорядок рядом с сингулярностью и может ли порядок удержаться там, где обычное описание ломается.",
 },
 "popular": {
    "seen": "Построено течение, у которого скорость уходит в бесконечность за конечное время при гладкой внешней силе, из покоя и с конечной энергией. Сингулярность живёт в игле, сжимающейся быстрее, чем разгоняется, а недостающую силу поставляет сама жидкость через среднее напряжение колебательных импульсов. Для нас это первый строго построенный пример локальной сингулярности сплошной среды при конечной энергии, с которым можно работать дальше.",
    "strength": "Механизм явный: вихрь-игла, кольцо, две семьи импульсов, тепловая внешность. Значит, его можно переносить: считать эффективную метрику, спрашивать, что с ним делает исчезающая вязкость, и пробовать воспроизвести в лаборатории.",
    "directions": [
        {"text": "Связь с общей теорией относительности. С 1981 года известно, что возмущения в движущейся жидкости бегут по эффективной метрике, а горизонты и излучение Хокинга воспроизводят в воде и в атомных облаках. Следующий шаг напрашивается: посчитать акустическую метрику построенного течения. Игла с расходящейся скоростью и исчезающей энергией — кандидат на точку, где эффективная метрика теряет гладкость, то есть на лабораторный аналог сингулярности пространства-времени с конечной энергией. Граница честная: аналоговая гравитация переносит поведение полей на кривом фоне, а не уравнения Эйнштейна, и именно поэтому вопрос решаемый.", "based_on": B1},
        {"text": "Сингулярность как центр антиэнтропии. Рабочая гипотеза: локальная сингулярность — окно, где второе начало перестаёт быть абсолютным и порядок может рождаться из хаоса. У построенного течения есть прямая проверка: бюджет энтропии отдельно в ядре, в кольце и снаружи. Энергия вносится силой, глобальный баланс положителен; вопрос в области, где локальное производство энтропии отрицательно и удерживается импульсами. Если она есть и её размер следует масштабам работы, «центр антиэнтропии» становится измеримой величиной.", "based_on": B2},
        {"text": "Сверхтекучее и конденсат Бозе–Эйнштейна. В классической жидкости вязкость съедает импульсы, и это часть конструкции; в сверхтекучем гелии и в конденсате вязкость исчезает, вихри квантуются, сами собираются в решётки, квантовая турбулентность наблюдается в лаборатории. Отсюда мысль: там, где диссипации нет, сингулярность может не рассеяться, а удержаться. Программа: перенести механизм кольцевых импульсов в уравнение Гросса–Питаевского и найти, что заменяет вязкое гашение.", "based_on": B3},
        {"text": "Макроскопический резонатор. Два встречно вращающихся колеса в противофазе — принудительное вращательное течение со сдвигом, тот самый фон, на котором растут импульсы по центробежному механизму. Измерить можно напрямую: напряжение Рейнольдса в кольце и его зависимость от скорости вращения. Совпадение знака и роста с конструкцией было бы первой лабораторной точкой; аналоговая «бомба» в чашке с водоворотом показывает, что такие измерения делаются.", "based_on": B4},
        {"text": "Два пути к одной двери. Резонатор в метрике и резонатор в квантовой жидкости описываются одной математикой: фон со сдвигом, кольцо, колебания, поставляющие напряжение. Стоит собрать таблицу соответствий: что в игле отвечает горизонту, что квантованному вихрю, что накачке. Так видно, какая дверь ближе к эксперименту, а какая к теории.", "based_on": B5},
    ],
    "ideas": [
        "Вывести акустическую метрику построенного течения и проверить, уходит ли её кривизна в бесконечность при t → 1.",
        "Посчитать локальное производство энтропии по трём зонам конструкции и найти область с отрицательным балансом.",
        "Повторить механизм кольцевых импульсов в модели Гросса–Питаевского при нулевой вязкости.",
        "Собрать вращающуюся установку со встречными приводами и измерить напряжение Рейнольдса в кольце.",
    ],
    "significance": "Если сингулярность течения переносится на эффективную метрику, обычная и квантовая жидкости становятся стендом для вопросов, которые в самой гравитации не проверить: как ведёт себя энтропия рядом с сингулярностью и может ли порядок удерживаться там, где непрерывное описание ломается. Работа OpenAI впервые даёт такому стенду явную, строго построенную сингулярность с конечной энергией.",
 },
},
"en": {
 "simple": {
    "seen": "A whirlpool was built that reaches infinite speed in finite time while its energy keeps shrinking. A smooth outside force pushes it, and the missing force is produced by the water itself, through small oscillations around the core. For us this is the first honestly built point where the ordinary description of a fluid breaks, and it can be worked with further.",
    "strength": "The mechanism is visible as a whole: the needle, the ring around it, the oscillations, calm water outside. What can be seen can be recomputed another way, repeated in another medium and tried by hand.",
    "directions": [
        {"text": "The link to gravity. For forty years it has been known that waves in flowing water behave as if the space around them were curved, and in a bathtub or in a cloud of cold atoms one can make real 'horizons' like those of a black hole. So the needle in this work also has its own 'curvature', and it can be computed. If it goes to infinity at the moment of the blowup, we have a laboratory model of a singularity, as in general relativity, only with finite energy. The honest caveat: this is a model of how waves behave, not Einstein's gravity itself.", "based_on": B1},
        {"text": "A point where order may be born from chaos. There is a thought: at such a special point the second law of thermodynamics may stop being strict, and disorder there may decrease rather than grow. With this work it can be checked directly: count how much disorder is produced separately in the needle, in the ring and outside. The outside force puts energy into the water, so disorder grows overall; the question is whether there is a region inside where it falls and is held by the oscillations. If there is, a 'centre of anti-entropy' becomes a number rather than words.", "based_on": B2},
        {"text": "A fluid without friction. In ordinary water friction damps the oscillations, and the proof is built on that. In superfluid helium and in a Bose–Einstein condensate there is no friction: vortices there are quantized, they line up into lattices by themselves, and quantum turbulence, order among chaos, is observed in the laboratory. Hence the idea: where there is nothing to damp it, a special point may not disperse but hold. This can be tested on the equation used to describe a condensate.", "based_on": B3},
        {"text": "A tabletop setup. Two wheels rotating against each other create exactly the sheared flow on which the oscillations in the paper grow. One concrete number can be measured: how the oscillations in the ring transport rotation at different wheel speeds. Agreement with the calculation would be the first point from the laboratory. Similar measurements have already been made on a whirlpool in a cup.", "based_on": B4},
        {"text": "Two paths to one door. The setup with wheels and the superfluid are described by the same mathematics: both have sheared rotation, a ring and oscillations. It is worth making a table: what in the needle corresponds to the horizon, to a quantized vortex, to the outside pumping. Then one sees which path is closer to experiment and which to theory.", "based_on": B5},
    ],
    "ideas": [
        "Compute the 'curvature' of the needle as for waves in water and see whether it goes to infinity at the blowup.",
        "Count where exactly in the construction disorder is produced and where it might decrease.",
        "Repeat the oscillation mechanism in a condensate model where there is no friction.",
        "Build a tank with two counter-rotating drives and measure the transport of rotation in the ring.",
    ],
    "significance": "If the special point in water transfers to 'curvature', ordinary and quantum fluids become a testbed for questions that cannot be checked in real gravity: how disorder behaves next to a singularity and whether order can hold where the ordinary description breaks.",
 },
 "popular": {
    "seen": "A flow is constructed whose speed goes to infinity in finite time under a smooth external force, from rest and with finite energy. The singularity lives in a needle that shrinks faster than it speeds up, and the missing force is supplied by the fluid itself through the mean stress of oscillatory pulses. For us this is the first rigorously built example of a local singularity of a continuous medium at finite energy, an object to keep working with.",
    "strength": "The mechanism is explicit: needle vortex, annulus, two families of pulses, heat exterior. So it can be transferred: compute its effective metric, ask what vanishing viscosity does to it, try to reproduce it in a laboratory.",
    "directions": [
        {"text": "The link to general relativity. Since 1981 it has been known that disturbances in a moving fluid run on an effective metric, and horizons and Hawking radiation are reproduced in water and in atomic clouds. The next step suggests itself: compute the acoustic metric of the constructed flow. A needle with divergent speed and vanishing energy is a candidate for a point where the effective metric loses smoothness, a laboratory analogue of a spacetime singularity at finite energy. The boundary is honest: analogue gravity transfers the behaviour of fields on a curved background, not Einstein's equations, and that is exactly why the question is solvable.", "based_on": B1},
        {"text": "The singularity as a centre of anti-entropy. Working hypothesis: a local singularity is a window where the second law stops being absolute and order can be born from chaos. The constructed flow admits a direct test: the entropy budget separately in the core, in the annulus and outside. Energy is injected by the force, the global balance is positive; the question is about a region where local entropy production is negative and held by the pulses. If it exists and its size follows the scalings of the paper, a 'centre of anti-entropy' becomes a measurable quantity.", "based_on": B2},
        {"text": "Superfluids and Bose–Einstein condensates. In a classical fluid viscosity eats the pulses, and that is part of the construction; in superfluid helium and in a condensate viscosity vanishes, vortices are quantized, they self-assemble into lattices, quantum turbulence is observed in the laboratory. Hence the thought: where there is no dissipation, the singularity may not disperse but hold. Programme: carry the annulus-pulse mechanism into the Gross–Pitaevskii equation and find what replaces viscous damping.", "based_on": B3},
        {"text": "A macroscopic resonator. Two counter-rotating wheels in antiphase are a driven rotating shear flow, the very background on which the pulses grow by the centrifugal mechanism. It can be measured directly: the Reynolds stress in the annulus and its dependence on rotation speed. Agreement of sign and growth with the construction would be the first laboratory point; the analogue 'bomb' in a cup with a whirlpool shows such measurements are done.", "based_on": B4},
        {"text": "Two paths to one door. A resonator in the metric and a resonator in a quantum fluid are described by one mathematics: a sheared background, an annulus, oscillations supplying stress. It is worth building a correspondence table: what in the needle answers to the horizon, to a quantized vortex, to the pumping. Then one sees which door is closer to experiment and which to theory.", "based_on": B5},
    ],
    "ideas": [
        "Derive the acoustic metric of the constructed flow and check whether its curvature diverges as t → 1.",
        "Compute local entropy production over the three zones of the construction and look for a region with negative balance.",
        "Repeat the annulus-pulse mechanism in a Gross–Pitaevskii model at zero viscosity.",
        "Build a rotating tank with counter-rotating drives and measure the Reynolds stress in the annulus.",
    ],
    "significance": "If a flow singularity transfers to an effective metric, ordinary and quantum fluids become a testbed for questions that cannot be tested in gravity itself: how entropy behaves next to a singularity and whether order can hold where the continuous description breaks. OpenAI's paper gives such a testbed, for the first time, an explicit, rigorously built singularity at finite energy.",
 },
},
"es": {
 "simple": {
    "seen": "Se construyó un remolino que alcanza velocidad infinita en tiempo finito aunque su energía no deja de encogerse. Lo empuja una fuerza externa suave, y la fuerza que falta la produce el propio agua con pequeñas oscilaciones alrededor del núcleo. Para nosotros es el primer punto construido con honestidad donde la descripción ordinaria de un fluido se rompe, y con él se puede seguir trabajando.",
    "strength": "El mecanismo se ve entero: la aguja, el anillo a su alrededor, las oscilaciones, el agua tranquila fuera. Lo que se ve se puede recalcular de otro modo, repetir en otro medio e intentar montar con las manos.",
    "directions": [
        {"text": "La conexión con la gravedad. Desde hace cuarenta años se sabe que las ondas en agua que fluye se comportan como si el espacio alrededor estuviera curvado, y en una bañera o en una nube de átomos fríos se fabrican «horizontes» reales como los de un agujero negro. Así que la aguja de este trabajo también tiene su propia «curvatura», y se puede calcular. Si en el instante de la explosión se va al infinito, tenemos un modelo de laboratorio de una singularidad, como en la relatividad general, solo que con energía finita. La salvedad honesta: es un modelo de cómo se comportan las ondas, no la gravedad de Einstein en sí.", "based_on": B1},
        {"text": "Un punto donde el orden puede nacer del caos. Hay una idea: en un punto tan especial la segunda ley de la termodinámica puede dejar de ser estricta, y el desorden allí no crece sino que disminuye. Con este trabajo se puede comprobar directamente: contar cuánto desorden nace por separado en la aguja, en el anillo y fuera. La fuerza externa mete energía en el agua, así que en conjunto el desorden crece; la pregunta es si hay dentro una región donde cae y lo sostienen las oscilaciones. Si la hay, un «centro de antientropía» pasa a ser un número y no palabras.", "based_on": B2},
        {"text": "Un fluido sin fricción. En el agua ordinaria la fricción apaga las oscilaciones, y sobre eso se construye la prueba. En el helio superfluido y en un condensado de Bose–Einstein no hay fricción: los vórtices están cuantizados, se alinean solos en redes, y la turbulencia cuántica, orden entre el caos, se observa en el laboratorio. De ahí la idea: donde no hay nada que apague, un punto especial puede no dispersarse sino sostenerse. Se puede probar en la ecuación con que se describe un condensado.", "based_on": B3},
        {"text": "Un montaje de mesa. Dos ruedas que giran en sentidos opuestos crean justo el flujo con cizalla sobre el que crecen las oscilaciones del trabajo. Se puede medir un número concreto: cómo las oscilaciones del anillo transportan rotación a distintas velocidades de las ruedas. La coincidencia con el cálculo sería el primer punto del laboratorio. Medidas parecidas ya se han hecho con un remolino en una taza.", "based_on": B4},
        {"text": "Dos caminos a una misma puerta. El montaje con ruedas y el superfluido se describen con la misma matemática: ambos tienen rotación con cizalla, un anillo y oscilaciones. Vale la pena hacer una tabla: qué en la aguja corresponde al horizonte, al vórtice cuantizado, al bombeo externo. Entonces se ve qué camino está más cerca del experimento y cuál de la teoría.", "based_on": B5},
    ],
    "ideas": [
        "Calcular la «curvatura» de la aguja como para ondas en agua y ver si se va al infinito en la explosión.",
        "Contar dónde exactamente nace el desorden en la construcción y dónde quizá disminuye.",
        "Repetir el mecanismo de oscilaciones en un modelo de condensado donde no hay fricción.",
        "Montar un tanque con dos accionamientos contrarrotantes y medir el transporte de rotación en el anillo.",
    ],
    "significance": "Si el punto especial en el agua se traslada a la «curvatura», los fluidos ordinarios y cuánticos se convierten en banco de pruebas para preguntas que en la gravedad real no se pueden comprobar: cómo se comporta el desorden junto a una singularidad y si el orden puede sostenerse donde la descripción ordinaria se rompe.",
 },
 "popular": {
    "seen": "Se construye un flujo cuya velocidad se va al infinito en tiempo finito bajo una fuerza externa suave, desde el reposo y con energía finita. La singularidad vive en una aguja que se encoge más rápido de lo que acelera, y la fuerza que falta la aporta el propio fluido mediante la tensión media de pulsos oscilatorios. Para nosotros es el primer ejemplo construido con rigor de una singularidad local de un medio continuo con energía finita, un objeto con el que seguir trabajando.",
    "strength": "El mecanismo es explícito: vórtice-aguja, anillo, dos familias de pulsos, exterior de calor. Así que se puede trasladar: calcular su métrica efectiva, preguntar qué le hace la viscosidad que se anula, intentar reproducirlo en el laboratorio.",
    "directions": [
        {"text": "La conexión con la relatividad general. Desde 1981 se sabe que las perturbaciones en un fluido en movimiento corren sobre una métrica efectiva, y los horizontes y la radiación de Hawking se reproducen en agua y en nubes atómicas. El siguiente paso se impone: calcular la métrica acústica del flujo construido. Una aguja con velocidad divergente y energía que se anula es candidata a punto donde la métrica efectiva pierde suavidad, un análogo de laboratorio de una singularidad del espacio-tiempo con energía finita. El límite es honesto: la gravedad análoga traslada el comportamiento de los campos sobre un fondo curvo, no las ecuaciones de Einstein, y justo por eso la pregunta es resoluble.", "based_on": B1},
        {"text": "La singularidad como centro de antientropía. Hipótesis de trabajo: una singularidad local es una ventana donde la segunda ley deja de ser absoluta y el orden puede nacer del caos. El flujo construido admite una prueba directa: el balance de entropía por separado en el núcleo, en el anillo y fuera. La energía la inyecta la fuerza, el balance global es positivo; la cuestión es una región donde la producción local de entropía es negativa y la sostienen los pulsos. Si existe y su tamaño sigue las escalas del trabajo, un «centro de antientropía» pasa a ser una magnitud medible.", "based_on": B2},
        {"text": "Superfluidos y condensados de Bose–Einstein. En un fluido clásico la viscosidad se come los pulsos, y eso es parte de la construcción; en el helio superfluido y en un condensado la viscosidad se anula, los vórtices se cuantizan, se autoensamblan en redes, la turbulencia cuántica se observa en el laboratorio. De ahí la idea: donde no hay disipación, la singularidad puede no dispersarse sino sostenerse. Programa: llevar el mecanismo de pulsos anulares a la ecuación de Gross–Pitaevskii y hallar qué sustituye a la amortiguación viscosa.", "based_on": B3},
        {"text": "Un resonador macroscópico. Dos ruedas contrarrotantes en contrafase son un flujo rotatorio forzado con cizalla, el mismo fondo sobre el que crecen los pulsos por el mecanismo centrífugo. Se puede medir directamente: la tensión de Reynolds en el anillo y su dependencia de la velocidad de rotación. La coincidencia de signo y crecimiento con la construcción sería el primer punto de laboratorio; la «bomba» análoga en una taza con remolino muestra que tales medidas se hacen.", "based_on": B4},
        {"text": "Dos caminos a una misma puerta. Un resonador en la métrica y un resonador en un fluido cuántico se describen con una misma matemática: fondo con cizalla, anillo, oscilaciones que aportan tensión. Vale la pena construir una tabla de correspondencias: qué en la aguja responde al horizonte, al vórtice cuantizado, al bombeo. Así se ve qué puerta está más cerca del experimento y cuál de la teoría.", "based_on": B5},
    ],
    "ideas": [
        "Derivar la métrica acústica del flujo construido y comprobar si su curvatura diverge cuando t → 1.",
        "Calcular la producción local de entropía en las tres zonas de la construcción y buscar una región con balance negativo.",
        "Repetir el mecanismo de pulsos anulares en un modelo de Gross–Pitaevskii con viscosidad cero.",
        "Montar un tanque rotatorio con accionamientos contrarrotantes y medir la tensión de Reynolds en el anillo.",
    ],
    "significance": "Si una singularidad del flujo se traslada a una métrica efectiva, los fluidos ordinarios y cuánticos se convierten en banco de pruebas para preguntas que en la propia gravedad no se pueden probar: cómo se comporta la entropía junto a una singularidad y si el orden puede sostenerse donde la descripción continua se rompe. El trabajo de OpenAI da a ese banco, por primera vez, una singularidad explícita y rigurosamente construida con energía finita.",
 },
},
"ar": {
 "simple": {
    "seen": "بُنيت دوامة تبلغ سرعة لانهائية في زمن منتهٍ رغم أن طاقتها لا تكف عن التناقص. تدفعها قوة خارجية ملساء، والقوة الناقصة ينتجها الماء نفسه باهتزازات صغيرة حول النواة. هذه عندنا أول نقطة مبنية بأمانة ينكسر عندها الوصف العادي للمائع، ويمكن مواصلة العمل عليها.",
    "strength": "الآلية مرئية بكاملها: الإبرة، والحلقة حولها، والاهتزازات، والماء الهادئ في الخارج. وما يُرى يمكن إعادة حسابه بطريقة أخرى، وتكراره في وسط آخر، ومحاولة تركيبه باليد.",
    "directions": [
        {"text": "الصلة بالجاذبية. منذ أربعين عامًا معروف أن الموجات في الماء الجاري تسلك كأن الفضاء حولها منحنٍ، وأن في حوض الاستحمام أو في سحابة من الذرات الباردة يمكن صنع «آفاق» حقيقية كآفاق الثقب الأسود. إذن للإبرة في هذا العمل «انحناؤها» الخاص، ويمكن حسابه. فإن مضى إلى اللانهاية لحظة الانفجار، كان أمامنا نموذج مختبري لتفرّد كما في النسبية العامة، لكن بطاقة منتهية. التحفظ الأمين: هذا نموذج لسلوك الموجات، لا جاذبية أينشتاين نفسها.", "based_on": B1},
        {"text": "نقطة قد يولد فيها النظام من الفوضى. ثمة فكرة: عند نقطة خاصة كهذه قد يكف القانون الثاني للترموديناميكا عن الصرامة، فلا تنمو الفوضى هناك بل تنقص. مع هذا العمل يمكن التحقق مباشرة: حساب مقدار الفوضى المتولدة على حدة في الإبرة وفي الحلقة وفي الخارج. القوة الخارجية تضخ الطاقة في الماء، فالفوضى في المجمل تنمو؛ والسؤال هل ثمة منطقة في الداخل تنقص فيها وتمسكها الاهتزازات. إن وُجدت، صار «مركز مضاد الإنتروبيا» رقمًا لا كلامًا.", "based_on": B2},
        {"text": "مائع بلا احتكاك. في الماء العادي يخمد الاحتكاك الاهتزازات، وعلى ذلك بُني البرهان. أما في الهيليوم الفائق وفي مكثف بوز–أينشتاين فلا احتكاك: الدوامات هناك مكمّمة، وتصطف وحدها في شبكات، والاضطراب الكمي، النظام وسط الفوضى، يُرصد في المختبر. ومن هنا الفكرة: حيث لا شيء يخمد، قد لا تتبدد النقطة الخاصة بل تصمد. ويمكن اختبار ذلك على المعادلة التي يوصف بها المكثف.", "based_on": B3},
        {"text": "جهاز على الطاولة. عجلتان تدوران متعاكستين تصنعان بالضبط الجريان ذا القص الذي تنمو عليه الاهتزازات في العمل. يمكن قياس رقم واحد محدد: كيف تنقل الاهتزازات في الحلقة الدوران عند سرعات مختلفة للعجلتين. التوافق مع الحساب سيكون أول نقطة من المختبر. وقياسات مشابهة أُجريت بالفعل على دوامة في كوب.", "based_on": B4},
        {"text": "طريقان إلى باب واحد. الجهاز ذو العجلتين والمائع الفائق تصفهما رياضيات واحدة: لكليهما دوران بقص وحلقة واهتزازات. يجدر إعداد جدول: ما الذي يقابل في الإبرة الأفق، والدوامة المكمّمة، والضخ الخارجي. عندها يُرى أي الطريقين أقرب إلى التجربة وأيهما إلى النظرية.", "based_on": B5},
    ],
    "ideas": [
        "حساب «انحناء» الإبرة كما للموجات في الماء والنظر هل يمضي إلى اللانهاية لحظة الانفجار.",
        "حساب أين بالضبط تتولد الفوضى في البناء وأين ربما تنقص.",
        "تكرار آلية الاهتزازات في نموذج مكثف لا احتكاك فيه.",
        "بناء حوض بمحركين متعاكسين وقياس نقل الدوران في الحلقة.",
    ],
    "significance": "إن انتقلت النقطة الخاصة في الماء إلى «انحناء»، صارت الموائع العادية والكمية منصة اختبار لأسئلة لا تُختبر في الجاذبية الحقيقية: كيف تسلك الفوضى بجوار التفرّد، وهل يمكن للنظام أن يصمد حيث ينكسر الوصف العادي.",
 },
 "popular": {
    "seen": "بُني جريان تمضي سرعته إلى اللانهاية في زمن منتهٍ تحت قوة خارجية ملساء، من السكون وبطاقة منتهية. يسكن التفرّد إبرةً تنكمش أسرع مما تتسارع، والقوة الناقصة يوفرها المائع نفسه عبر الإجهاد المتوسط لنبضات اهتزازية. هذا عندنا أول مثال مبني بصرامة على تفرّد موضعي لوسط متصل بطاقة منتهية، شيء يمكن مواصلة العمل عليه.",
    "strength": "الآلية صريحة: دوامة إبرية، حلقة، عائلتان من النبضات، خارج حراري. إذن يمكن نقلها: حساب متريتها الفعّالة، والسؤال عما تفعله بها اللزوجة المتلاشية، ومحاولة إعادة إنتاجها في المختبر.",
    "directions": [
        {"text": "الصلة بالنسبية العامة. منذ 1981 معروف أن الاضطرابات في مائع متحرك تجري على مترية فعّالة، وأن الآفاق وإشعاع هوكينغ يُستنسخان في الماء وفي السحب الذرية. الخطوة التالية تفرض نفسها: حساب المترية الصوتية للجريان المبني. إبرة بسرعة متباعدة وطاقة متلاشية مرشحة لتكون نقطة تفقد فيها المترية الفعّالة سلاستها، نظيرًا مختبريًا لتفرّد الزمكان بطاقة منتهية. الحد أمين: الجاذبية التناظرية تنقل سلوك الحقول على خلفية منحنية لا معادلات أينشتاين، ولهذا بالذات يكون السؤال قابلًا للحل.", "based_on": B1},
        {"text": "التفرّد مركزًا لمضاد الإنتروبيا. فرضية عمل: التفرّد الموضعي نافذة يكف فيها القانون الثاني عن أن يكون مطلقًا ويمكن للنظام أن يولد من الفوضى. للجريان المبني اختبار مباشر: ميزانية الإنتروبيا على حدة في النواة وفي الحلقة وفي الخارج. الطاقة تُحقن بالقوة والميزان الشامل موجب؛ والسؤال عن منطقة يكون فيها إنتاج الإنتروبيا الموضعي سالبًا وتمسكه النبضات. إن وُجدت وتبع حجمها مقاييس العمل، صار «مركز مضاد الإنتروبيا» كمية قابلة للقياس.", "based_on": B2},
        {"text": "السوائل الفائقة ومكثفات بوز–أينشتاين. في المائع الكلاسيكي تلتهم اللزوجة النبضات، وهذا جزء من البناء؛ وفي الهيليوم الفائق وفي المكثف تتلاشى اللزوجة، وتتكمّم الدوامات، وتتجمع ذاتيًا في شبكات، ويُرصد الاضطراب الكمي في المختبر. ومن هنا الفكرة: حيث لا تبديد، قد لا يتبدد التفرّد بل يصمد. البرنامج: نقل آلية النبضات الحلقية إلى معادلة غروس–بيتايفسكي وإيجاد ما يحل محل الإخماد اللزج.", "based_on": B3},
        {"text": "مرنان ماكروسكوبي. عجلتان متعاكستا الدوران في تضاد طوري هما جريان دوراني مدفوع بقص، الخلفية نفسها التي تنمو عليها النبضات بالآلية الطاردة المركزية. يمكن القياس مباشرة: إجهاد رينولدز في الحلقة وتبعيته لسرعة الدوران. توافق الإشارة والنمو مع البناء سيكون أول نقطة مختبرية؛ و«القنبلة» التناظرية في كوب فيه دوامة تبيّن أن مثل هذه القياسات تُجرى.", "based_on": B4},
        {"text": "طريقان إلى باب واحد. مرنان في المترية ومرنان في مائع كمي تصفهما رياضيات واحدة: خلفية بقص، حلقة، اهتزازات توفر الإجهاد. يجدر بناء جدول تقابلات: ما يقابل الأفق في الإبرة، وما يقابل الدوامة المكمّمة، وما يقابل الضخ. عندها يُرى أي الباب أقرب إلى التجربة وأيهما إلى النظرية.", "based_on": B5},
    ],
    "ideas": [
        "اشتقاق المترية الصوتية للجريان المبني والتحقق هل يتباعد انحناؤها عندما t → 1.",
        "حساب إنتاج الإنتروبيا الموضعي في المناطق الثلاث للبناء والبحث عن منطقة بميزان سالب.",
        "تكرار آلية النبضات الحلقية في نموذج غروس–بيتايفسكي بلزوجة صفرية.",
        "بناء حوض دوار بمحركات متعاكسة وقياس إجهاد رينولدز في الحلقة.",
    ],
    "significance": "إن انتقل تفرّد الجريان إلى مترية فعّالة، صارت الموائع العادية والكمية منصة اختبار لأسئلة لا تُختبر في الجاذبية نفسها: كيف تسلك الإنتروبيا بجوار التفرّد، وهل يمكن للنظام أن يصمد حيث ينكسر الوصف المتصل. يمنح عمل OpenAI هذه المنصة، لأول مرة، تفرّدًا صريحًا مبنيًا بصرامة بطاقة منتهية.",
 },
},
"fr": {
 "simple": {
    "seen": "Un tourbillon a été construit qui atteint une vitesse infinie en temps fini alors que son énergie ne cesse de diminuer. Une force extérieure lisse le pousse, et la force manquante est produite par l'eau elle-même, par de petites oscillations autour du cœur. Pour nous, c'est le premier point construit honnêtement où la description ordinaire d'un fluide se brise, et on peut continuer à travailler avec.",
    "strength": "Le mécanisme est visible en entier : l'aiguille, l'anneau autour, les oscillations, l'eau calme au dehors. Ce qui se voit peut être recalculé autrement, répété dans un autre milieu et essayé à la main.",
    "directions": [
        {"text": "Le lien avec la gravité. Depuis quarante ans on sait que les ondes dans une eau qui coule se comportent comme si l'espace autour était courbé, et que dans une baignoire ou dans un nuage d'atomes froids on fabrique de vrais « horizons » comme ceux d'un trou noir. Donc l'aiguille de ce travail a aussi sa propre « courbure », et on peut la calculer. Si elle part à l'infini à l'instant de l'explosion, nous avons un modèle de laboratoire d'une singularité, comme en relativité générale, mais à énergie finie. La réserve honnête : c'est un modèle du comportement des ondes, pas la gravité d'Einstein elle-même.", "based_on": B1},
        {"text": "Un point où l'ordre peut naître du chaos. Il y a une idée : en un tel point particulier, le second principe de la thermodynamique peut cesser d'être strict, et le désordre n'y croît pas mais diminue. Avec ce travail on peut le vérifier directement : compter combien de désordre naît séparément dans l'aiguille, dans l'anneau et au dehors. La force extérieure met de l'énergie dans l'eau, donc dans l'ensemble le désordre croît ; la question est de savoir s'il existe à l'intérieur une région où il tombe et est tenu par les oscillations. Si oui, un « centre d'anti-entropie » devient un nombre et non des mots.", "based_on": B2},
        {"text": "Un fluide sans frottement. Dans l'eau ordinaire le frottement éteint les oscillations, et la preuve est bâtie là-dessus. Dans l'hélium superfluide et dans un condensat de Bose–Einstein il n'y a pas de frottement : les tourbillons y sont quantifiés, ils s'alignent d'eux-mêmes en réseaux, et la turbulence quantique, ordre parmi le chaos, s'observe en laboratoire. D'où l'idée : là où rien n'éteint, un point particulier peut ne pas se disperser mais tenir. On peut le tester sur l'équation qui décrit un condensat.", "based_on": B3},
        {"text": "Un montage de table. Deux roues tournant en sens contraires créent exactement l'écoulement cisaillé sur lequel croissent les oscillations du travail. On peut mesurer un nombre concret : comment les oscillations de l'anneau transportent la rotation à différentes vitesses des roues. Un accord avec le calcul serait le premier point venu du laboratoire. Des mesures semblables ont déjà été faites sur un tourbillon dans une tasse.", "based_on": B4},
        {"text": "Deux chemins vers une même porte. Le montage à roues et le superfluide sont décrits par la même mathématique : tous deux ont une rotation cisaillée, un anneau et des oscillations. Il vaut la peine de dresser une table : ce qui, dans l'aiguille, correspond à l'horizon, au tourbillon quantifié, au pompage extérieur. On voit alors quel chemin est le plus proche de l'expérience et lequel de la théorie.", "based_on": B5},
    ],
    "ideas": [
        "Calculer la « courbure » de l'aiguille comme pour des ondes dans l'eau et voir si elle part à l'infini à l'explosion.",
        "Compter où exactement, dans la construction, le désordre naît et où il diminue peut-être.",
        "Reproduire le mécanisme des oscillations dans un modèle de condensat sans frottement.",
        "Monter une cuve à deux entraînements contrarotatifs et mesurer le transport de rotation dans l'anneau.",
    ],
    "significance": "Si le point particulier dans l'eau se transfère à la « courbure », les fluides ordinaires et quantiques deviennent un banc d'essai pour des questions invérifiables dans la vraie gravité : comment le désordre se comporte près d'une singularité et si l'ordre peut tenir là où la description ordinaire se brise.",
 },
 "popular": {
    "seen": "Un écoulement est construit dont la vitesse part à l'infini en temps fini sous une force extérieure lisse, depuis le repos et à énergie finie. La singularité vit dans une aiguille qui rétrécit plus vite qu'elle n'accélère, et la force manquante est fournie par le fluide lui-même via la contrainte moyenne d'impulsions oscillatoires. Pour nous, c'est le premier exemple rigoureusement construit d'une singularité locale d'un milieu continu à énergie finie, un objet avec lequel continuer à travailler.",
    "strength": "Le mécanisme est explicite : tourbillon-aiguille, anneau, deux familles d'impulsions, extérieur de chaleur. Il peut donc être transféré : calculer sa métrique effective, demander ce qu'en fait une viscosité qui s'annule, tenter de le reproduire en laboratoire.",
    "directions": [
        {"text": "Le lien avec la relativité générale. Depuis 1981 on sait que les perturbations d'un fluide en mouvement courent sur une métrique effective, et que les horizons et le rayonnement de Hawking se reproduisent dans l'eau et dans des nuages atomiques. L'étape suivante s'impose : calculer la métrique acoustique de l'écoulement construit. Une aiguille à vitesse divergente et énergie évanescente est candidate au point où la métrique effective perd sa régularité, un analogue de laboratoire d'une singularité de l'espace-temps à énergie finie. La limite est honnête : la gravité analogue transporte le comportement des champs sur un fond courbe, pas les équations d'Einstein, et c'est justement pourquoi la question est soluble.", "based_on": B1},
        {"text": "La singularité comme centre d'anti-entropie. Hypothèse de travail : une singularité locale est une fenêtre où le second principe cesse d'être absolu et où l'ordre peut naître du chaos. L'écoulement construit admet un test direct : le bilan d'entropie séparément dans le cœur, dans l'anneau et à l'extérieur. L'énergie est injectée par la force, le bilan global est positif ; la question porte sur une région où la production locale d'entropie est négative et tenue par les impulsions. Si elle existe et que sa taille suit les échelles du travail, un « centre d'anti-entropie » devient une grandeur mesurable.", "based_on": B2},
        {"text": "Superfluides et condensats de Bose–Einstein. Dans un fluide classique la viscosité dévore les impulsions, et cela fait partie de la construction ; dans l'hélium superfluide et dans un condensat la viscosité s'annule, les tourbillons sont quantifiés, ils s'auto-assemblent en réseaux, la turbulence quantique s'observe en laboratoire. D'où l'idée : là où il n'y a pas de dissipation, la singularité peut ne pas se disperser mais tenir. Programme : porter le mécanisme des impulsions annulaires dans l'équation de Gross–Pitaevskii et trouver ce qui remplace l'amortissement visqueux.", "based_on": B3},
        {"text": "Un résonateur macroscopique. Deux roues contrarotatives en opposition de phase forment un écoulement tournant forcé avec cisaillement, le fond même sur lequel croissent les impulsions par le mécanisme centrifuge. On peut mesurer directement : la contrainte de Reynolds dans l'anneau et sa dépendance à la vitesse de rotation. Un accord du signe et de la croissance avec la construction serait le premier point de laboratoire ; la « bombe » analogue dans une tasse avec tourbillon montre que de telles mesures se font.", "based_on": B4},
        {"text": "Deux chemins vers une même porte. Un résonateur dans la métrique et un résonateur dans un fluide quantique sont décrits par une seule mathématique : fond cisaillé, anneau, oscillations fournissant la contrainte. Il vaut la peine de dresser une table de correspondances : ce qui, dans l'aiguille, répond à l'horizon, au tourbillon quantifié, au pompage. On voit alors quelle porte est la plus proche de l'expérience et laquelle de la théorie.", "based_on": B5},
    ],
    "ideas": [
        "Dériver la métrique acoustique de l'écoulement construit et vérifier si sa courbure diverge quand t → 1.",
        "Calculer la production locale d'entropie sur les trois zones de la construction et chercher une région à bilan négatif.",
        "Reproduire le mécanisme des impulsions annulaires dans un modèle de Gross–Pitaevskii à viscosité nulle.",
        "Monter une cuve tournante à entraînements contrarotatifs et mesurer la contrainte de Reynolds dans l'anneau.",
    ],
    "significance": "Si une singularité d'écoulement se transfère à une métrique effective, les fluides ordinaires et quantiques deviennent un banc d'essai pour des questions intestables dans la gravité elle-même : comment l'entropie se comporte près d'une singularité et si l'ordre peut tenir là où la description continue se brise. Le travail d'OpenAI donne à ce banc, pour la première fois, une singularité explicite, rigoureusement construite, à énergie finie.",
 },
},
}
